title: "Umang Dakh"
email: umang501dakh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Currently, focus on Cloud computing Industry. 
  Core team member of Script foundation Jaipur chapter. 
  Starting New buisness name - Ananda organo
baseurl: "/" 
url: "https://umangdakh.gitub.io/" 
twitter_username: Denny_UD
github_username:  Denny-UD

sass:
  sass_dir: _sass

icon: assets/img/logo (2).png
